version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: carrental-postgres
    environment:
      POSTGRES_DB: carrental
      POSTGRES_USER: carrental
      POSTGRES_PASSWORD: carrental
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carrental -d carrental"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:latest
    container_name: carrental-adminer
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  postgres_data:
